import type { Discourse, Category, Playlist } from '@/types'

export const categories: Category[] = [
  { id: '1', name: 'Meditation', slug: 'meditation', icon: 'brain', color: '#E8E0D4', count: 245, description: 'Guided and silent meditation discourses' },
  { id: '2', name: 'Awareness', slug: 'awareness', icon: 'eye', color: '#D4E0E8', count: 189, description: 'Wake up to your true nature' },
  { id: '3', name: 'Love', slug: 'love', icon: 'heart', color: '#F0E0E0', count: 167, description: 'Love as a path to liberation' },
  { id: '4', name: 'Silence', slug: 'silence', icon: 'moon', color: '#E0E8F0', count: 134, description: 'The art of inner stillness' },
  { id: '5', name: 'Anxiety', slug: 'anxiety', icon: 'wind', color: '#F0ECE0', count: 98, description: 'Find peace beyond worry' },
  { id: '6', name: 'Ego', slug: 'ego', icon: 'sparkles', color: '#E8E4E0', count: 156, description: 'Dissolving the false self' },
  { id: '7', name: 'Life & Death', slug: 'life-death', icon: 'infinity', color: '#E0E8E4', count: 112, description: 'Embracing existence fully' },
  { id: '8', name: 'Zen', slug: 'zen', icon: 'circle', color: '#F0EDE8', count: 89, description: 'Direct pointing to reality' },
  { id: '9', name: 'Tantra', slug: 'tantra', icon: 'flame', color: '#F0E8E4', count: 76, description: 'The path of total acceptance' },
  { id: '10', name: 'Creativity', slug: 'creativity', icon: 'feather', color: '#E8F0E8', count: 65, description: 'Unbound creative expression' },
  { id: '11', name: 'Relationships', slug: 'relationships', icon: 'users', color: '#F0E8F0', count: 143, description: 'Conscious connection with others' },
  { id: '12', name: 'Business', slug: 'business', icon: 'briefcase', color: '#E8E8F0', count: 54, description: 'Wisdom for the modern world' },
]

export const discourses: Discourse[] = [
  {
    id: '1',
    title: 'A Bird on the Wing 01',
    series: 'A Bird on the Wing',
    seriesSlug: 'a-bird-on-the-wing-01-11',
    trackNumber: 1,
    duration: '1h 37m',
    durationSeconds: 5869,
    category: 'Meditation',
    tags: ['death', 'meditation', 'awareness', 'silence'],
    mood: ['peaceful', 'deep', 'contemplative'],
    thumbnail: 'https://img.youtube.com/vi/y47LgoRtQmY/maxresdefault.jpg',
    gradient: 'from-[#E8DFD0] to-[#F5F0EB]',
    audioUrl: 'https://oshoworld.com/wp-content/uploads/newAudios/A_Bird_on_the_Wing_(11)/A_Bird_on_the_Wing__01.mp3',
    date: '1972-04-15',
    language: 'english',
    description: 'A profound exploration of death as the ultimate meditation. Osho guides us to see death not as an end but as a gateway to the divine.',
    summary: 'In this discourse, Osho explores death as the ultimate meditation. He explains that death is not an enemy but a gateway, and by learning to die consciously, we learn to live fully.',
    highlights: [
      { time: '12:20', text: 'Death is not the opposite of life, but the opposite of birth. Life is eternal.' },
      { time: '26:10', text: 'The fear of death is not really the fear of death — it is the fear of losing the ego.' },
      { time: '45:30', text: 'Meditation is a taste of death. You die to the past, you die to the future, you die to the mind.' },
    ],
    chapters: [
      { time: '0:00', title: 'Introduction' },
      { time: '12:20', title: 'Death as Meditation' },
      { time: '26:10', title: 'The Ego and Fear' },
      { time: '45:30', title: 'Dying Consciously' },
      { time: '1:10:00', title: 'The Art of Living and Dying' },
    ],
    listenCount: 84500,
    speaker: 'Osho',
  },
  {
    id: '2',
    title: 'A Bird on the Wing 02',
    series: 'A Bird on the Wing',
    seriesSlug: 'a-bird-on-the-wing-01-11',
    trackNumber: 2,
    duration: '1h 25m',
    durationSeconds: 5125,
    category: 'Awareness',
    tags: ['mind', 'awareness', 'witnessing', 'meditation'],
    mood: ['focused', 'peaceful', 'awakening'],
    thumbnail: 'https://img.youtube.com/vi/s-o-1s5K2xA/maxresdefault.jpg',
    gradient: 'from-[#D4E0E8] to-[#E8F0F5]',
    audioUrl: 'https://oshoworld.com/wp-content/uploads/newAudios/A_Bird_on_the_Wing_(11)/A_Bird_on_the_Wing__02.mp3',
    date: '1974-06-22',
    language: 'english',
    description: 'Learn the art of witnessing your own mind without judgment or attachment.',
    summary: 'Osho teaches the art of witnessing — watching the mind without identification. He explains that the watcher is not the mind, and this realization is freedom.',
    highlights: [
      { time: '8:15', text: 'The mind is a beautiful instrument. But it is a servant, not the master.' },
      { time: '22:40', text: 'Watching the mind is the only way to go beyond the mind.' },
      { time: '38:00', text: 'Thoughts are like clouds passing in the sky. You are the sky, not the clouds.' },
    ],
    chapters: [
      { time: '0:00', title: 'Introduction' },
      { time: '8:15', title: 'Mind as a Servant' },
      { time: '22:40', title: 'The Art of Witnessing' },
      { time: '38:00', title: 'Freedom from the Mind' },
    ],
    listenCount: 72300,
    speaker: 'Osho',
  },
  {
    id: '3',
    title: 'A Bird on the Wing 03',
    series: 'A Bird on the Wing',
    seriesSlug: 'a-bird-on-the-wing-01-11',
    trackNumber: 3,
    duration: '1h 45m',
    durationSeconds: 6346,
    category: 'Love',
    tags: ['love', 'relationship', 'freedom', 'tantra'],
    mood: ['warm', 'deep', 'heartfelt'],
    thumbnail: 'https://img.youtube.com/vi/rEZ7FKpfG8Q/maxresdefault.jpg',
    gradient: 'from-[#EDD8D8] to-[#F8F0F0]',
    audioUrl: 'https://oshoworld.com/wp-content/uploads/newAudios/A_Bird_on_the_Wing_(11)/A_Bird_on_the_Wing__03.mp3',
    date: '1975-02-14',
    language: 'english',
    description: 'A radical redefinition of love beyond attachment, possession, and expectation.',
    summary: 'Osho distinguishes between love as a state of being and love as a relationship. True love is not a bond but a freedom, not a possession but a sharing.',
    highlights: [
      { time: '5:30', text: 'Love is not a relationship. Love is a state of being.' },
      { time: '18:45', text: 'When love becomes a relationship, it becomes a prison. When love is your being, it is freedom.' },
      { time: '34:20', text: 'The other is not the cause of your love. The other is just an excuse for your love to flower.' },
    ],
    chapters: [
      { time: '0:00', title: 'Love vs Relationship' },
      { time: '5:30', title: 'Love as Being' },
      { time: '18:45', title: 'Freedom in Love' },
      { time: '34:20', title: 'Love Blossoming' },
    ],
    listenCount: 112000,
    speaker: 'Osho',
  },
  {
    id: '4',
    title: 'A Bird on the Wing 04',
    series: 'A Bird on the Wing',
    seriesSlug: 'a-bird-on-the-wing-01-11',
    trackNumber: 4,
    duration: '1h 34m',
    durationSeconds: 5646,
    category: 'Silence',
    tags: ['silence', 'stillness', 'awareness', 'buddha'],
    mood: ['peaceful', 'calm', 'serene'],
    thumbnail: 'https://img.youtube.com/vi/7IZulhCis1k/hqdefault.jpg',
    gradient: 'from-[#D6E0EC] to-[#EDF2F8]',
    audioUrl: 'https://oshoworld.com/wp-content/uploads/newAudios/A_Bird_on_the_Wing_(11)/A_Bird_on_the_Wing__04.mp3',
    date: '1976-08-10',
    language: 'english',
    description: 'Dive into the profound silence that lies beneath all thought and feeling.',
    summary: 'Osho takes us into the heart of silence. He explains that silence is not the absence of noise, but the presence of being itself.',
    highlights: [
      { time: '10:00', text: 'Silence is not something empty. It is full of presence, full of life.' },
      { time: '25:30', text: 'When you are silent, the whole universe speaks to you.' },
      { time: '50:15', text: 'Knowing is not from the mind. Knowing arises when silence meets existence.' },
    ],
    chapters: [
      { time: '0:00', title: 'The Nature of Silence' },
      { time: '10:00', title: 'Silence as Presence' },
      { time: '25:30', title: 'Listening to the Universe' },
      { time: '50:15', title: 'Knowing Beyond Mind' },
    ],
    listenCount: 63400,
    speaker: 'Osho',
  },
  {
    id: '5',
    title: 'A Bird on the Wing 05',
    series: 'A Bird on the Wing',
    seriesSlug: 'a-bird-on-the-wing-01-11',
    trackNumber: 5,
    duration: '1h 29m',
    durationSeconds: 5372,
    category: 'Anxiety',
    tags: ['fear', 'anxiety', 'courage', 'trust'],
    mood: ['soothing', 'reassuring', 'empowering'],
    thumbnail: 'https://img.youtube.com/vi/nIHByJxzQpc/maxresdefault.jpg',
    gradient: 'from-[#E8E0D0] to-[#F8F4EC]',
    audioUrl: 'https://oshoworld.com/wp-content/uploads/newAudios/A_Bird_on_the_Wing_(11)/A_Bird_on_the_Wing__05.mp3',
    date: '1977-03-25',
    language: 'english',
    description: 'Transform your relationship with fear and discover the courage to be.',
    summary: 'Osho addresses the root of all anxiety — the fear of being oneself. He offers profound insights into living with trust and courage.',
    highlights: [
      { time: '7:45', text: 'Fear is simply the absence of trust in existence.' },
      { time: '20:15', text: 'The greatest courage is to be yourself in a world that wants you to be like everyone else.' },
      { time: '42:30', text: 'Anxiety is the price you pay for living in the past and future. The present is always peaceful.' },
    ],
    chapters: [
      { time: '0:00', title: 'Understanding Fear' },
      { time: '7:45', title: 'Trust in Existence' },
      { time: '20:15', title: 'The Courage to Be' },
      { time: '42:30', title: 'The Peace of the Present' },
    ],
    listenCount: 95600,
    speaker: 'Osho',
  },
  {
    id: '6',
    title: 'A Bird on the Wing 06',
    series: 'A Bird on the Wing',
    seriesSlug: 'a-bird-on-the-wing-01-11',
    trackNumber: 6,
    duration: '1h 40m',
    durationSeconds: 6008,
    category: 'Ego',
    tags: ['ego', 'self', 'identity', 'dissolution'],
    mood: ['deep', 'challenging', 'revealing'],
    thumbnail: 'https://img.youtube.com/vi/uEHuZjykLy0/maxresdefault.jpg',
    gradient: 'from-[#DFDCD8] to-[#F2EEE8]',
    audioUrl: 'https://oshoworld.com/wp-content/uploads/newAudios/A_Bird_on_the_Wing_(11)/A_Bird_on_the_Wing__06.mp3',
    date: '1978-11-08',
    language: 'english',
    description: 'See through the illusion of the ego and discover your authentic self.',
    summary: 'Osho dismantles the concept of ego, showing it to be a collection of borrowed ideas and false identities. He guides us toward authentic being.',
    highlights: [
      { time: '9:00', text: 'The ego is a phantom. It has no substance — it is just a habit of identification.' },
      { time: '28:30', text: 'You are born authentic, then the world teaches you to be fake. The spiritual journey is a return to authenticity.' },
      { time: '55:00', text: 'The death of the ego is the birth of the self.' },
    ],
    chapters: [
      { time: '0:00', title: 'What is Ego?' },
      { time: '9:00', title: 'The Phantom Self' },
      { time: '28:30', title: 'Return to Authenticity' },
      { time: '55:00', title: 'Death and Rebirth' },
    ],
    listenCount: 78100,
    speaker: 'Osho',
  },
  {
    id: '7',
    title: 'A Bird on the Wing 07',
    series: 'A Bird on the Wing',
    seriesSlug: 'a-bird-on-the-wing-01-11',
    trackNumber: 7,
    duration: '1h 36m',
    durationSeconds: 5778,
    category: 'Life & Death',
    tags: ['life', 'risk', 'freedom', 'courage'],
    mood: ['energizing', 'inspiring', 'freeing'],
    thumbnail: 'https://img.youtube.com/vi/iahwRhFyaIc/hqdefault.jpg',
    gradient: 'from-[#D6E2DC] to-[#ECF4F0]',
    audioUrl: 'https://oshoworld.com/wp-content/uploads/newAudios/A_Bird_on_the_Wing_(11)/A_Bird_on_the_Wing__07.mp3',
    date: '1975-05-12',
    language: 'english',
    description: 'Why playing safe is the greatest risk, and how to embrace life fully.',
    summary: 'Osho challenges the human tendency to play safe. He argues that security is death and that life only flowers when we live dangerously, fully, without holding back.',
    highlights: [
      { time: '6:20', text: 'Playing safe is the greatest risk. By trying to protect yourself, you destroy yourself.' },
      { time: '19:45', text: 'Life is only for those who are ready to risk. The coward dies every moment, the brave dies only once.' },
      { time: '41:00', text: 'The moment you accept that you are alone, you become free. Free from the crowd, free from fear.' },
    ],
    chapters: [
      { time: '0:00', title: 'The Illusion of Safety' },
      { time: '6:20', title: 'Risk and Reward' },
      { time: '19:45', title: 'The Courage to Live' },
      { time: '41:00', title: 'Solo Journey' },
    ],
    listenCount: 56800,
    speaker: 'Osho',
  },
  {
    id: '8',
    title: 'A Bird on the Wing 08',
    series: 'A Bird on the Wing',
    seriesSlug: 'a-bird-on-the-wing-01-11',
    trackNumber: 8,
    duration: '1h 30m',
    durationSeconds: 5454,
    category: 'Meditation',
    tags: ['home', 'being', 'presence', 'buddha'],
    mood: ['peaceful', 'warm', 'grounding'],
    thumbnail: 'https://img.youtube.com/vi/NxVPSJTEtwg/maxresdefault.jpg',
    gradient: 'from-[#DFD6C8] to-[#F0EBE0]',
    audioUrl: 'https://oshoworld.com/wp-content/uploads/newAudios/A_Bird_on_the_Wing_(11)/A_Bird_on_the_Wing__08.mp3',
    date: '1979-01-20',
    language: 'english',
    description: 'A gentle guide to returning to your true home — the present moment.',
    summary: 'Osho speaks about coming home — not to a physical place, but to yourself. He guides listeners back to the present moment, the only true home.',
    highlights: [
      { time: '4:30', text: 'Home is not a place in the world. Home is a place in your being.' },
      { time: '16:50', text: 'The mind is always travelling. Coming home means coming out of the mind.' },
      { time: '33:20', text: 'When you are here now, you are home. There is nowhere else to go.' },
    ],
    chapters: [
      { time: '0:00', title: 'The Search for Home' },
      { time: '4:30', title: 'Home Within' },
      { time: '16:50', title: 'Out of the Mind' },
      { time: '33:20', title: 'Here and Now' },
    ],
    listenCount: 68900,
    speaker: 'Osho',
  },
  {
    id: '9',
    title: 'A Bird on the Wing 09',
    series: 'A Bird on the Wing',
    seriesSlug: 'a-bird-on-the-wing-01-11',
    trackNumber: 9,
    duration: '1h 31m',
    durationSeconds: 5505,
    category: 'Meditation',
    tags: ['meditation', 'techniques', 'practice', 'door'],
    mood: ['focused', 'practical', 'peaceful'],
    thumbnail: 'https://img.youtube.com/vi/M8EfTk8Ep88/maxresdefault.jpg',
    gradient: 'from-[#CDDCD0] to-[#E8F0EC]',
    audioUrl: 'https://oshoworld.com/wp-content/uploads/newAudios/A_Bird_on_the_Wing_(11)/A_Bird_on_the_Wing__09.mp3',
    date: '1976-12-05',
    language: 'english',
    description: 'Practical wisdom on meditation techniques for modern seekers.',
    summary: 'Osho provides clear, practical guidance on meditation. He explains that meditation is not a technique but a state of being, and offers ways to enter this state.',
    highlights: [
      { time: '3:45', text: 'Meditation is not something you do. It is something you become.' },
      { time: '15:30', text: 'All techniques are just pointers. They are like a finger pointing to the moon. Do not mistake the finger for the moon.' },
      { time: '40:00', text: 'Sitting silently, doing nothing, the spring comes and the grass grows by itself.' },
    ],
    chapters: [
      { time: '0:00', title: 'What Meditation Is Not' },
      { time: '3:45', title: 'Being vs Doing' },
      { time: '15:30', title: 'Techniques are Pointers' },
      { time: '40:00', title: 'Effortless Presence' },
    ],
    listenCount: 123400,
    speaker: 'Osho',
  },
  {
    id: '10',
    title: 'A Bird on the Wing 10',
    series: 'A Bird on the Wing',
    seriesSlug: 'a-bird-on-the-wing-01-11',
    trackNumber: 10,
    duration: '1h 45m',
    durationSeconds: 6317,
    category: 'Zen',
    tags: ['uncertainty', 'mystery', 'trust', 'surrender'],
    mood: ['freeing', 'deep', 'expansive'],
    thumbnail: 'https://img.youtube.com/vi/fXeKNPq12Bw/maxresdefault.jpg',
    gradient: 'from-[#E8E4DC] to-[#F8F5F0]',
    audioUrl: 'https://oshoworld.com/wp-content/uploads/newAudios/A_Bird_on_the_Wing_(11)/A_Bird_on_the_Wing__10.mp3',
    date: '1977-09-18',
    language: 'english',
    description: 'Finding the beauty and freedom in not knowing.',
    summary: 'Osho celebrates uncertainty as the door to mystery. He shows how the mind craves certainty, but the soul thrives in the unknown, the mysterious, the uncertain.',
    highlights: [
      { time: '8:00', text: 'Certainty is the death of wonder. Uncertainty is the beginning of awe.' },
      { time: '22:15', text: 'The mind wants to know. The heart wants to experience. Knowledge is safe, experience is dangerous.' },
      { time: '47:40', text: 'Only those who can live with uncertainty can know the divine. The divine is the ultimate uncertainty.' },
    ],
    chapters: [
      { time: '0:00', title: 'The Mind and Certainty' },
      { time: '8:00', title: 'The Beauty of Not Knowing' },
      { time: '22:15', title: 'Knowledge vs Experience' },
      { time: '47:40', title: 'The Ultimate Uncertainty' },
    ],
    listenCount: 44500,
    speaker: 'Osho',
  },
  {
    id: '11',
    title: 'Let Go of the Struggle',
    series: 'Sufis: The People of the Path',
    duration: '1h 14m',
    durationSeconds: 4440,
    category: 'Awareness',
    tags: ['surrender', 'effort', 'letting go', 'sufi'],
    mood: ['releasing', 'peaceful', 'light'],
    thumbnail: 'https://img.youtube.com/vi/HY9aw5cQRDQ/hqdefault.jpg',
    gradient: 'from-[#D8D8EC] to-[#ECECF8]',
    audioUrl: '',
    date: '1978-04-30',
    language: 'english',
    description: 'Why all spiritual striving is counterproductive and how to simply allow.',
    summary: 'Osho turns the spiritual search on its head, suggesting that all effort to achieve is counterproductive. True transformation happens not through struggle but through letting go.',
    highlights: [
      { time: '6:50', text: 'The very effort to be free is a bondage. Drop the effort and you are free.' },
      { time: '19:30', text: 'You cannot become enlightened. You can only realize that you have always been enlightened.' },
      { time: '38:10', text: 'Surrender is not a giving up. It is a giving in to existence.' },
    ],
    chapters: [
      { time: '0:00', title: 'The Trap of Effort' },
      { time: '6:50', title: 'Freedom Without Effort' },
      { time: '19:30', title: 'Already Enlightened' },
      { time: '38:10', title: 'The Art of Surrender' },
    ],
    listenCount: 51200,
    speaker: 'Osho',
  },
  {
    id: '12',
    title: 'Women: The Mysterious Door',
    series: 'Tantra: The Way of Acceptance',
    duration: '1h 35m',
    durationSeconds: 5700,
    category: 'Tantra',
    tags: ['feminine', 'mystery', 'tantra', 'acceptance'],
    mood: ['reverent', 'deep', 'expansive'],
    thumbnail: 'https://img.youtube.com/vi/MM3VopzjC1k/maxresdefault.jpg',
    gradient: 'from-[#E8DCD6] to-[#F8F0EC]',
    audioUrl: '',
    date: '1975-08-16',
    language: 'english',
    description: 'A radical tantric exploration of the feminine as the gateway to the divine.',
    summary: 'Osho explores the feminine principle as the door to the divine. He celebrates the mystery of womanhood and shows how tantra sees the feminine as the ultimate expression of existence.',
    highlights: [
      { time: '8:30', text: 'The feminine is the door to the divine. Not through logic, but through love.' },
      { time: '25:00', text: 'Woman is the most mysterious phenomenon in existence. She cannot be understood, she can only be experienced.' },
      { time: '52:20', text: 'Tantra accepts everything. It does not deny the body, it does not deny desire. It transforms everything into prayer.' },
    ],
    chapters: [
      { time: '0:00', title: 'The Feminine Principle' },
      { time: '8:30', title: 'Mystery of Woman' },
      { time: '25:00', title: 'Beyond Understanding' },
      { time: '52:20', title: 'Acceptance as Prayer' },
    ],
    listenCount: 38700,
    speaker: 'Osho',
  },
  {
    id: '13',
    title: 'साक्षी रहो (Be a Witness)',
    series: 'अमृत अनुभव (Experience of the Nectar)',
    duration: '1h 10m',
    durationSeconds: 4200,
    category: 'Awareness',
    tags: ['witnessing', 'awareness', 'hindi', 'sakshi'],
    mood: ['peaceful', 'focused', 'awakening'],
    thumbnail: '',
    gradient: 'from-[#3D5A5C] to-[#6B8F8F]',
    audioUrl: '',
    date: '1976-03-15',
    language: 'hindi',
    description: 'The essence of all meditation — being a witness to your own mind.',
    summary: 'Osho explains the core of all spiritual practices: witnessing. In Hindi, he beautifully articulates how to remain a witness to thoughts, emotions, and actions.',
    highlights: [
      { time: '5:15', text: 'साक्षी होना ही ध्यान का सार है।' },
      { time: '18:40', text: 'तुम वह नहीं हो जो तुम सोचते हो। तुम वह हो जो इन सबको देख रहा है।' },
    ],
    chapters: [
      { time: '0:00', title: 'प्रस्तावना' },
      { time: '5:15', title: 'साक्षी भाव' },
      { time: '18:40', title: 'सोचने वाला और देखने वाला' },
    ],
    listenCount: 156000,
    speaker: 'Osho',
  },
  {
    id: '14',
    title: 'प्रेम ही परम धर्म (Love is the Ultimate Religion)',
    series: 'प्रेम का प्रवेश (The Door of Love)',
    duration: '1h 25m',
    durationSeconds: 5100,
    category: 'Love',
    tags: ['love', 'religion', 'heart', 'hindi'],
    mood: ['warm', 'devotional', 'expansive'],
    thumbnail: '',
    gradient: 'from-[#8B3A3A] to-[#C16666]',
    audioUrl: '',
    date: '1977-07-20',
    language: 'hindi',
    description: 'Love as the highest spiritual path — beyond all religions and doctrines.',
    summary: 'Osho places love above all religions. He says love is not a commandment but a natural flowering, and when love happens, the divine is not far behind.',
    highlights: [
      { time: '10:20', text: 'प्रेम कोई कर्तव्य नहीं है। प्रेम तो तुम्हारी स्वाभाविक अभिव्यक्ति है।' },
      { time: '34:15', text: 'जब प्रेम होता है, तब धर्म की कोई आवश्यकता नहीं रहती। प्रेम ही परम धर्म है।' },
    ],
    chapters: [
      { time: '0:00', title: 'प्रेम और धर्म' },
      { time: '10:20', title: 'प्रेम: कर्तव्य या अभिव्यक्ति?' },
      { time: '34:15', title: 'प्रेम ही परम धर्म' },
    ],
    listenCount: 134000,
    speaker: 'Osho',
  },
  {
    id: '15',
    title: 'You Are the Light',
    series: 'Zen: The Path of Paradox',
    duration: '1h 16m',
    durationSeconds: 4560,
    category: 'Zen',
    tags: ['zen', 'enlightenment', 'self', 'being'],
    mood: ['awakening', 'clear', 'direct'],
    thumbnail: 'https://img.youtube.com/vi/bzxcT4PNysk/hqdefault.jpg',
    gradient: 'from-[#E6E2DA] to-[#F5F2EC]',
    audioUrl: '',
    date: '1978-12-02',
    language: 'english',
    description: 'Direct pointing to your own enlightened nature.',
    summary: 'Osho points directly to the truth that you are already what you are seeking. The search itself is the obstacle. You are the light you have been looking for.',
    highlights: [
      { time: '7:10', text: 'You are the light. There is nothing to achieve, nothing to become. Just recognize what you already are.' },
      { time: '21:30', text: 'The search is the disease. Stop searching and you will find. Drop the seeking and you are the sought.' },
      { time: '39:45', text: 'Enlightenment is not an addition. It is a recognition. It is coming home to your own nature.' },
    ],
    chapters: [
      { time: '0:00', title: 'The Search' },
      { time: '7:10', title: 'You Are the Light' },
      { time: '21:30', title: 'Drop the Seeking' },
      { time: '39:45', title: 'Recognition' },
    ],
    listenCount: 52300,
    speaker: 'Osho',
  },
]

export const featuredDiscourses = [
  discourses[0],
  discourses[10],
  discourses[11],
  discourses[14],
  discourses[4],
]
export const trendingDiscourses = [...discourses].sort((a, b) => b.listenCount - a.listenCount)
export const meditationDiscourses = discourses.filter(d => d.category === 'Meditation')
export const loveDiscourses = discourses.filter(d => d.category === 'Love')
export const awarenessDiscourses = discourses.filter(d => d.category === 'Awareness')
export const hindiDiscourses = discourses.filter(d => d.language === 'hindi')
export const englishDiscourses = discourses.filter(d => d.language === 'english')

export const playlists: Playlist[] = [
  {
    id: 'p1',
    title: 'Beginner\'s Journey',
    description: 'Start your inner exploration with these essential discourses',
    thumbnail: '',
    gradient: 'from-[#7A1A2E] to-[#5C0F20]',
    count: 8,
    duration: '8h 45m',
    category: 'meditation',
  },
  {
    id: 'p2',
    title: 'Osho on Love',
    description: 'The most beautiful discourses on love, intimacy and connection',
    thumbnail: '',
    gradient: 'from-[#D4515F] to-[#A83240]',
    count: 12,
    duration: '14h 20m',
    category: 'love',
  },
  {
    id: 'p3',
    title: 'For Deep Sleep',
    description: 'Calming discourses to drift into peaceful sleep',
    thumbnail: '',
    gradient: 'from-[#2C4A5A] to-[#1A2F3E]',
    count: 6,
    duration: '7h 30m',
    category: 'meditation',
  },
  {
    id: 'p4',
    title: 'Anxiety Relief',
    description: 'Find peace beyond worry with these transformative talks',
    thumbnail: '',
    gradient: 'from-[#5A4A3A] to-[#3E3028]',
    count: 10,
    duration: '11h 50m',
    category: 'anxiety',
  },
  {
    id: 'p5',
    title: 'Hindi Classics',
    description: 'Osho\'s most beloved Hindi discourses',
    thumbnail: '',
    gradient: 'from-[#B8862D] to-[#8B6914]',
    count: 15,
    duration: '18h 40m',
    category: 'hindi',
  },
  {
    id: 'p6',
    title: 'Awareness & Witnessing',
    description: 'Master the art of consciousness',
    thumbnail: '',
    gradient: 'from-[#3C5A6B] to-[#264050]',
    count: 9,
    duration: '10h 15m',
    category: 'awareness',
  },
]

export const moods = [
  { id: 'm1', name: 'Peaceful', icon: 'moon', color: '#D4E0E8' },
  { id: 'm2', name: 'Anxious', icon: 'wind', color: '#F0ECE0' },
  { id: 'm3', name: 'Lonely', icon: 'heart', color: '#F0E0E0' },
  { id: 'm4', name: 'Overthinking', icon: 'brain', color: '#E8E4E0' },
  { id: 'm5', name: 'Seeking', icon: 'compass', color: '#E0E8E4' },
  { id: 'm6', name: 'Grateful', icon: 'sun', color: '#F0EDE8' },
  { id: 'm7', name: 'Confused', icon: 'help-circle', color: '#E0E0F0' },
  { id: 'm8', name: 'Hopeful', icon: 'sparkles', color: '#E8F0E8' },
]

export const beginnerPaths = [
  {
    id: 'b1',
    title: 'Peace & Calm',
    description: 'For those seeking inner stillness',
    icon: 'moon',
  },
  {
    id: 'b2',
    title: 'Better Sleep',
    description: 'Let go of the day and rest deeply',
    icon: 'bed-double',
  },
  {
    id: 'b3',
    title: 'Love & Relationships',
    description: 'Understand the art of conscious love',
    icon: 'heart',
  },
  {
    id: 'b4',
    title: 'Anxiety Relief',
    description: 'Find freedom from worry and fear',
    icon: 'wind',
  },
  {
    id: 'b5',
    title: 'Meditation Basics',
    description: 'Your first steps into meditation',
    icon: 'brain',
  },
  {
    id: 'b6',
    title: 'Focus & Clarity',
    description: 'Sharpen your mind and awareness',
    icon: 'target',
  },
]

export const dailyQuote = {
  text: "The moment you accept yourself as you are, all your tensions disappear. Accepting yourself is the beginning of all transformation.",
  author: "Osho",
  discourse: "The Book of Wisdom",
}

export const dailyQuotes = [
  dailyQuote,
  {
    text: "Intelligence is the natural state of being alive. It is not something that has to be achieved; it is something that has to be allowed to happen.",
    author: "Osho",
    discourse: "Intelligence: The Creative Response to Now",
  },
  {
    text: "Courage is the most important quality, because without courage you cannot practice any other virtue consistently.",
    author: "Osho",
    discourse: "Courage: The Joy of Living Dangerously",
  },
  {
    text: "The greatest fear in the world is of the opinions of others. And the moment you are unafraid of the crowd, you are no longer a sheep.",
    author: "Osho",
    discourse: "Courage: The Joy of Living Dangerously",
  },
  {
    text: "Truth is not something outside to be discovered, it is something inside to be uncovered.",
    author: "Osho",
    discourse: "The True Sage",
  },
]
